2023-10-17 09:32:26,892 autofe.py:51 __init__ INFO | Namespace(cuda='0', train_size=0.7, epochs=300, ppo_epochs=10, episodes=24, lr=0.0001, entropy_weight=0.0001, baseline_weight=0.95, gama=0.9, gae_lambda=0.95, batch_size=4, d_model=128, d_k=32, d_v=32, d_ff=64, n_heads=6, worker=1, steps_num=3, combine=True, preprocess=False, seed=1, cv=5, cv_train_size=0.7, cv_seed=1, split_train_test=False, shuffle=False, enc_c_pth='', enc_d_pth='', mode='regression', model='rf', metric='rae', file_name='airfoil', c_columns=['V0', 'V1', 'V2', 'V3', 'V4'], d_columns=[], target='label')
2023-10-17 09:32:26,892 autofe.py:52 __init__ INFO | File name: airfoil
2023-10-17 09:32:26,892 autofe.py:53 __init__ INFO | Data shape: (1503, 6)
2023-10-17 09:32:28,628 autofe.py:120 set_cuda INFO | Use device: 0, cuda:0, NVIDIA GeForce RTX 4060 Laptop GPU
2023-10-17 09:32:28,628 autofe.py:110 __init__ INFO | Done AutoFE initialization.
2023-10-17 09:32:28,635 autofe.py:437 _get_cv_baseline INFO | Start getting CV baseline...
2023-10-17 09:32:29,053 main_attention.py:91 <module> INFO | Traceback (most recent call last):
  File "D:\python files\pythonProject3\FETCH\main_attention.py", line 88, in <module>
    autofe.fit_attention(args)
  File "D:\python files\pythonProject3\FETCH\autofe.py", line 139, in fit_attention
    score_b, scores_b = self._get_cv_baseline(df, args, mode, model, metric)
  File "D:\python files\pythonProject3\FETCH\autofe.py", line 520, in _get_cv_baseline
    scores = cross_val_score(model, X, y, cv=my_cv, scoring=rae_score)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 562, in cross_val_score
    cv_results = cross_validate(
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\utils\_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 328, in cross_validate
    _warn_or_raise_about_fit_failures(results, error_score)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 414, in _warn_or_raise_about_fit_failures
    raise ValueError(all_fits_failed_message)
ValueError: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\ensemble\_forest.py", line 456, in fit
    trees = Parallel(
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\utils\parallel.py", line 65, in __call__
    return super().__call__(iterable_with_config)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\parallel.py", line 1098, in __call__
    self.retrieve()
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "D:\software\anaconda\envs\pytorch\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "D:\software\anaconda\envs\pytorch\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.


--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\ensemble\_forest.py", line 456, in fit
    trees = Parallel(
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\sklearn\utils\parallel.py", line 65, in __call__
    return super().__call__(iterable_with_config)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\parallel.py", line 1008, in __call__
    n_jobs = self._initialize_backend()
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\parallel.py", line 775, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\_parallel_backends.py", line 506, in configure
    self._workers = get_memmapping_executor(
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\executor.py", line 20, in get_memmapping_executor
    return MemmappingExecutor.get_memmapping_executor(n_jobs, **kwargs)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\executor.py", line 42, in get_memmapping_executor
    manager = TemporaryResourcesManager(temp_folder)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\_memmapping_reducer.py", line 535, in __init__
    self.set_current_context(context_id)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\_memmapping_reducer.py", line 539, in set_current_context
    self.register_new_context(context_id)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\_memmapping_reducer.py", line 564, in register_new_context
    self.register_folder_finalizer(new_folder_path, context_id)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\_memmapping_reducer.py", line 594, in register_folder_finalizer
    resource_tracker.register(pool_subfolder, "folder")
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 178, in register
    self.ensure_running()
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 99, in ensure_running
    if self._check_alive():
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 170, in _check_alive
    self._send('PROBE', '', '')
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\joblib\externals\loky\backend\resource_tracker.py", line 197, in _send
    nbytes = os.write(self._fd, msg)
OSError: [Errno 22] Invalid argument


2023-10-17 09:32:29,054 main_attention.py:93 <module> INFO | Total cost time: 2.1632 s.
2023-10-17 09:32:33,736 autofe.py:51 __init__ INFO | Namespace(cuda='0', train_size=0.7, epochs=300, ppo_epochs=10, episodes=24, lr=0.0001, entropy_weight=0.0001, baseline_weight=0.95, gama=0.9, gae_lambda=0.95, batch_size=4, d_model=128, d_k=32, d_v=32, d_ff=64, n_heads=6, worker=1, steps_num=3, combine=True, preprocess=False, seed=1, cv=5, cv_train_size=0.7, cv_seed=1, split_train_test=False, shuffle=False, enc_c_pth='', enc_d_pth='', mode='regression', model='rf', metric='rae', file_name='airfoil', c_columns=['V0', 'V1', 'V2', 'V3', 'V4'], d_columns=[], target='label')
2023-10-17 09:32:33,736 autofe.py:52 __init__ INFO | File name: airfoil
2023-10-17 09:32:33,736 autofe.py:53 __init__ INFO | Data shape: (1503, 6)
2023-10-17 09:32:34,202 autofe.py:120 set_cuda INFO | Use device: 0, cuda:0, NVIDIA GeForce RTX 4060 Laptop GPU
2023-10-17 09:32:34,202 autofe.py:110 __init__ INFO | Done AutoFE initialization.
