2024-03-13 14:17:54,377 AutoFE.py:35 __init__ INFO | Namespace(cuda='0', epochs=100, ppo_epochs=20, episodes=4, file_name='hepatitis', mode='classify', model='rf', metric='f1', seed=1, train_size=0.7, cv=5, shuffle=False, d_model=128, d_k=32, d_v=32, d_ff=64, n_heads=6, worker=1, steps_num=5, lr=0.0001, entropy_weight=0.0001, baseline_weight=0.95, gama=0.9, gae_lambda=0.95, batch_size=4, c_columns=['V0', 'V13', 'V14', 'V15', 'V16', 'V17'], d_columns=['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V18'], target='label')
2024-03-13 14:17:54,377 AutoFE.py:36 __init__ INFO | File name: hepatitis
2024-03-13 14:17:54,377 AutoFE.py:37 __init__ INFO | Data shape: (155, 20)
2024-03-13 14:17:55,898 AutoFE.py:90 set_cuda INFO | Use device: 0, cuda:0, NVIDIA GeForce RTX 4060 Laptop GPU
2024-03-13 14:17:55,899 AutoFE.py:80 __init__ INFO | Done AutoFE initialization.
2024-03-13 14:17:55,955 AutoFE.py:103 fit_attention INFO | score_b=0.8129032258064516, scores_b=[0.80645161 0.80645161 0.87096774 0.70967742 0.87096774]
2024-03-13 14:17:57,346 main_ppo.py:80 <module> INFO | Traceback (most recent call last):
  File "D:\python files\pythonProject3\PPO_transformer_lstm\main_ppo.py", line 76, in <module>
    autofe.fit_attention(args)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\AutoFE.py", line 146, in fit_attention
    w_c = sample(args, self.ppo, pipline_args_train, df_c_encode, df_d_encode, df_t_norm, c_ops,d_ops,epoch, i, self.device)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\feature_engineer\training_ops.py", line 44, in sample
    df_c_encode, df_d_encode = pipline_ff.process_data(fe)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\process_data\pipeline_data.py", line 62, in process_data
    self.feature_combine()
  File "D:\python files\pythonProject3\PPO_transformer_lstm\process_data\pipeline_data.py", line 168, in feature_combine
    new_fe = generate_combine_fe(self.combine.iloc[:, [index, actions[1]]].values, feasible_values)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\process_data\feature_generate_memory.py", line 216, in generate_combine_fe
    ind = feasible_values[combine_feature_value]
KeyError: '58'

2024-03-13 14:17:57,347 main_ppo.py:82 <module> INFO | Total cost time: 2.9709 s.
