2024-03-11 14:31:16,650 AutoFE.py:35 __init__ INFO | Namespace(cuda='0', epochs=300, ppo_epochs=20, episodes=3, file_name='SPECTF', mode='classify', model='xgb', metric='f1', seed=1, train_size=0.7, cv=5, shuffle=False, d_model=128, d_k=32, d_v=32, d_ff=64, n_heads=6, worker=1, steps_num=10, lr=0.0001, entropy_weight=0.0001, baseline_weight=0.95, gama=0.9, gae_lambda=0.95, batch_size=4, c_columns=['V0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43'], d_columns=[], target='label')
2024-03-11 14:31:16,650 AutoFE.py:36 __init__ INFO | File name: SPECTF
2024-03-11 14:31:16,650 AutoFE.py:37 __init__ INFO | Data shape: (267, 45)
2024-03-11 14:31:18,177 AutoFE.py:91 set_cuda INFO | Use device: 0, cuda:0, NVIDIA GeForce RTX 4060 Laptop GPU
2024-03-11 14:31:18,177 AutoFE.py:81 __init__ INFO | Done AutoFE initialization.
2024-03-11 14:31:18,386 AutoFE.py:104 fit_attention INFO | score_b=0.7976939203354297, scores_b=[0.83333333 0.77777778 0.77358491 0.75471698 0.8490566 ]
2024-03-11 14:31:25,056 main_ppo.py:80 <module> INFO | Traceback (most recent call last):
  File "D:\python files\pythonProject3\PPO_transformer_lstm\main_ppo.py", line 76, in <module>
    autofe.fit_attention(args)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\AutoFE.py", line 149, in fit_attention
    w_c = sample(args, self.ppo, pipline_args_train, df_c_encode, df_d_encode, df_t_norm, c_ops,d_ops,epoch, i, self.device)
  File "D:\python files\pythonProject3\PPO_transformer_lstm\feature_engineer\training_ops.py", line 28, in sample
    df_encode = pd.concat(df_c_encode.drop(df_c_encode.columns[-1], axis=1) ,df_d_encode.drop(df_d_encode.columns[-1], axis=1),df_t_norm)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\reshape\concat.py", line 368, in concat
    op = _Concatenator(
  File "D:\software\anaconda\envs\pytorch\lib\site-packages\pandas\core\reshape\concat.py", line 403, in __init__
    raise TypeError(
TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

2024-03-11 14:31:25,712 main_ppo.py:82 <module> INFO | Total cost time: 8.7594 s.
