2023-10-16 23:50:29,238 autofe.py:54 __init__ INFO | Namespace(cuda='0', train_size=0.7, epochs=300, ppo_epochs=10, episodes=24, lr=0.0001, entropy_weight=0.0001, baseline_weight=0.95, gama=0.9, gae_lambda=0.95, batch_size=4, d_model=128, d_k=32, d_v=32, d_ff=64, n_heads=6, worker=1, steps_num=3, combine=True, preprocess=False, seed=1, cv=5, cv_train_size=0.7, cv_seed=1, split_train_test=False, shuffle=False, enc_c_pth='', enc_d_pth='', mode='regression', model='rf', metric='rae', file_name='airfoil', c_columns=['V0', 'V1', 'V2', 'V3', 'V4'], d_columns=[], target='label')
2023-10-16 23:50:29,238 autofe.py:55 __init__ INFO | File name: airfoil
2023-10-16 23:50:29,238 autofe.py:56 __init__ INFO | Data shape: (1503, 6)
2023-10-16 23:50:30,759 autofe.py:123 set_cuda INFO | Use device: 0, cuda:0, NVIDIA GeForce RTX 4060 Laptop GPU
2023-10-16 23:50:30,759 autofe.py:113 __init__ INFO | Done AutoFE initialization.
2023-10-16 23:50:30,766 autofe.py:440 _get_cv_baseline INFO | Start getting CV baseline...
2023-10-16 23:50:34,422 autofe.py:143 fit_attention INFO | score_b=0.5067697886469438, scores_b=[0.61519082 0.64949063 0.52346915 0.28065758 0.46504076]
2023-10-16 23:50:34,423 main_attention.py:92 <module> INFO | Traceback (most recent call last):
  File "D:\python files\pythonProject3\FETCH\main_attention.py", line 89, in <module>
    autofe.fit_attention(args)
  File "D:\python files\pythonProject3\FETCH\autofe.py", line 171, in fit_attention
    self.ppo = PPO(args, data_nums, operations_c, operations_d, d_model, d_k, d_v, d_ff, n_heads, self.device)
TypeError: 'module' object is not callable

2023-10-16 23:50:34,446 main_attention.py:94 <module> INFO | Total cost time: 5.208 s.
